'use strict';
require('dotenv').config();
const express = require('express');
const helmet = require('helmet');
const cors = require('cors');
const compression = require('compression');
const morgan = require('morgan');
const trainerRoutes = require('./routes/trainerRoutes');
const healthRoutes = require('./routes/healthRoutes');
const app = express();
app.use(helmet()); app.use(compression());
app.use(cors({ origin: (process.env.ALLOWED_ORIGINS || '').split(','), credentials: true }));
app.use(express.json({ limit: '10kb' }));
app.use(morgan(process.env.NODE_ENV === 'production' ? 'combined' : 'dev'));
app.use('/health', healthRoutes);
app.use('/api/trainers', trainerRoutes);
app.use((req, res) => res.status(404).json({ success: false, message: 'Route not found' }));
app.use((err, req, res, next) => res.status(err.status || 500).json({ success: false, message: err.message }));
module.exports = app;
